spring:
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true

      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # File size
      max-file-size: 200MB
      # File request Size
      max-request-size: 215MB

  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/gestiondocuments?createDatabaseIfNotExist=true&UserSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTime=UTC
    username: root
    password: "!@#$%^&*"
    driver-class-name: com.mysql.cj.jdbc.Driver
## specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
## Hibernate DDL Auto (create, create-drop, Update)
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081
